# Generated by Django 5.1.4 on 2024-12-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirstTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.IntegerField(default=15)),
                ('speach', models.IntegerField(default=45)),
                ('content', models.CharField(max_length=5120)),
            ],
        ),
        migrations.CreateModel(
            name='FourthTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.IntegerField(default=20)),
                ('speach', models.IntegerField(default=60)),
                ('audio', models.FileField(upload_to='toefl/audio')),
            ],
        ),
        migrations.CreateModel(
            name='SecondTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.IntegerField(default=30)),
                ('reading', models.IntegerField(default=40)),
                ('speach', models.IntegerField(default=60)),
                ('content', models.CharField(max_length=5120)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.IntegerField(default=30)),
                ('reading', models.IntegerField(default=45)),
                ('speach', models.IntegerField(default=60)),
                ('content', models.CharField(max_length=5120)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=1024)),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toefl.firsttask')),
                ('fourth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toefl.fourthtask')),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toefl.secondtask')),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toefl.thirdtask')),
            ],
        ),
    ]
