# Generated by Django 5.1.4 on 2024-12-21 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toefl', '0002_fourthtask_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='theme',
        ),
    ]
