# Generated by Django 5.1.4 on 2024-12-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ielts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstpart',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='secondpart',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='thirdpart',
            name='audio',
        ),
    ]
